name: Build Storybook Docs v2

on:
  push:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build-v2
